TE-8501: Fix pattern for extracting a directory name from namespace
spryker/router pull request #3
Opened 2021-01-27 16:36 UTC by qlmmlp

Ticket: [TE-8501](https://spryker.atlassian.net/browse/TE-8501)
## PR Description

2021-01-27 17:20 UTC, dereuromark requested changes
A backport on a minor (not latest release in a major series) is not a valid thing so far.
It is technically also not wise to do so, as it introduces sth that gets lost the next minors (which are supposed to be BC) and then introduced again some more minors on top.

As such we cannot continue this here.
For e.g. 2.x series any backport would go on top of 1.x series.

In this case, at least also 1.10.x would need to be fixed up as well ( https://release.spryker.com/module-versions?module_id=640&sort=key&direction=desc ) - but given semver we really never did this so far in between of minors.

2021-01-28 11:57 UTC, dereuromark approved these changes
Discussed, we can do this exception if we also patch up the 1.10.x versions.

2021-01-29 12:01 UTC, gechetspr approved these changes

2021-02-01 14:53 UTC, gechetspr commented
Released

2021-02-01 14:53 UTC, closed without merging